on:
  pull_request:
    branches:
      - production
  push:
    branches:
      - production
      - develop

name: Build & Release

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1  # Use the official Dart setup action
        with:
          sdk: '3.0.5' 

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5' # Adjust to your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Flutter Web
        run: flutter build web

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          files: "build/web/**/*" # Adjust to your build output path
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.Token }}
