name: Deploy to Github Pages

on:
  pull_request:
    branches:
      -production
  push:
    branches:
      -production
      -develop
name: "Build & Release"
jobs:
  build:
    name: "Build & Release"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
      - uses: actions/checkout@v2
       
      - name: Set Up Flutter
      - uses: subosito/flutter-action@v5
        with:
          flutter-version: '3.0.5'
      
      - name: Build Flutter Web
      - run: flutter pub get
      - run: flutter build web
      - name: push to Releases
        uses: ncipollo/release-action@v2
        with:
          artifacts: "build/web/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.Token }}

      





# push to production, 
# pull request on production